title: Hello LeetCode!
description: 我的 LeetCode 刷题记录
author: "Dongze Li"

theme: minima

base_url: /hello-leetcode

# Minima social links
twitter_username: ldgze
github_username: ldgze
linkedin_username: ldgze
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
